/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Destinations400
 */
interface Destinations400 {
  /** Message of the error */
  message?: string;
}

export class Destinations400Error extends ApiError<Destinations400> {}
