/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Destinations401
 */
interface Destinations401 {
  /** Message of the error */
  message?: string;
}

export class Destinations401Error extends ApiError<Destinations401> {}
