/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EsimDevice401
 */
interface EsimDevice401 {
  /** Message of the error */
  message?: string;
}

export class EsimDevice401Error extends ApiError<EsimDevice401> {}
