/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EsimMac401
 */
interface EsimMac401 {
  /** Message of the error */
  message?: string;
}

export class EsimMac401Error extends ApiError<EsimMac401> {}
