/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Esim400
 */
interface Esim400 {
  /** Message of the error */
  message?: string;
}

export class Esim400Error extends ApiError<Esim400> {}
