/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EsimHistory400
 */
interface EsimHistory400 {
  /** Message of the error */
  message?: string;
}

export class EsimHistory400Error extends ApiError<EsimHistory400> {}
