/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EsimDevice400
 */
interface EsimDevice400 {
  /** Message of the error */
  message?: string;
}

export class EsimDevice400Error extends ApiError<EsimDevice400> {}
