/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Esim401
 */
interface Esim401 {
  /** Message of the error */
  message?: string;
}

export class Esim401Error extends ApiError<Esim401> {}
