/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EsimHistory401
 */
interface EsimHistory401 {
  /** Message of the error */
  message?: string;
}

export class EsimHistory401Error extends ApiError<EsimHistory401> {}
