/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of EsimMac400
 */
interface EsimMac400 {
  /** Message of the error */
  message?: string;
}

export class EsimMac400Error extends ApiError<EsimMac400> {}
