/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Packages400
 */
interface Packages400 {
  /** Message of the error */
  message?: string;
}

export class Packages400Error extends ApiError<Packages400> {}
