/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PurchasesConsumption400
 */
interface PurchasesConsumption400 {
  /** Message of the error */
  message?: string;
}

export class PurchasesConsumption400Error extends ApiError<PurchasesConsumption400> {}
