/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PurchasesConsumption401
 */
interface PurchasesConsumption401 {
  /** Message of the error */
  message?: string;
}

export class PurchasesConsumption401Error extends ApiError<PurchasesConsumption401> {}
