/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of Purchases400
 */
interface Purchases400 {
  /** Message of the error */
  message?: string;
}

export class Purchases400Error extends ApiError<Purchases400> {}
