/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PurchasesTopup401
 */
interface PurchasesTopup401 {
  /** Message of the error */
  message?: string;
}

export class PurchasesTopup401Error extends ApiError<PurchasesTopup401> {}
