/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PurchasesEdit400
 */
interface PurchasesEdit400 {
  /** Message of the error */
  message?: string;
}

export class PurchasesEdit400Error extends ApiError<PurchasesEdit400> {}
