/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PurchasesEdit401
 */
interface PurchasesEdit401 {
  /** Message of the error */
  message?: string;
}

export class PurchasesEdit401Error extends ApiError<PurchasesEdit401> {}
