/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';

/**
 * Creates an instance of PurchasesTopup400
 */
interface PurchasesTopup400 {
  /** Message of the error */
  message?: string;
}

export class PurchasesTopup400Error extends ApiError<PurchasesTopup400> {}
