/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Destination, destinationSchema } from './destination';

export interface DestinationsResponse {
  destinations?: Destination[];
}

export const destinationsResponseSchema: Schema<DestinationsResponse> = object({
  destinations: [
    'destinations',
    optional(array(lazy(() => destinationSchema))),
  ],
});
