/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface Destination {
  /** Name of the destination */
  name?: string;
  /** ISO representation of the destination */
  destination?: string;
  supportedCountries?: string[];
}

export const destinationSchema: Schema<Destination> = object({
  name: ['name', optional(string())],
  destination: ['destination', optional(string())],
  supportedCountries: ['supportedCountries', optional(array(string()))],
});
