/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Device {
  /** Name of the OEM */
  oem?: string;
  /** Name of the Device */
  hardwareName?: string;
  /** Model of the Device */
  hardwareModel?: string;
  /** Serial Number of the eSIM */
  eid?: string;
}

export const deviceSchema: Schema<Device> = object({
  oem: ['oem', optional(string())],
  hardwareName: ['hardwareName', optional(string())],
  hardwareModel: ['hardwareModel', optional(string())],
  eid: ['eid', optional(string())],
});
