/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Esim {
  /** ID of the eSIM */
  iccid?: string;
}

export const esimSchema: Schema<Esim> = object({
  iccid: ['iccid', optional(string())],
});
