/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Esim3, esim3Schema } from './esim3';

export interface EsimMacResponse {
  esim?: Esim3;
}

export const esimMacResponseSchema: Schema<EsimMacResponse> = object({
  esim: ['esim', optional(lazy(() => esim3Schema))],
});
