/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Device, deviceSchema } from './device';

export interface EsimDeviceResponse {
  device?: Device;
}

export const esimDeviceResponseSchema: Schema<EsimDeviceResponse> = object({
  device: ['device', optional(lazy(() => deviceSchema))],
});
