/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Esim3 {
  /** ID of the eSIM */
  iccid?: string;
  /** SM-DP+ Address */
  smdpAddress?: string;
  /** The manual activation code */
  manualActivationCode?: string;
}

export const esim3Schema: Schema<Esim3> = object({
  iccid: ['iccid', optional(string())],
  smdpAddress: ['smdpAddress', optional(string())],
  manualActivationCode: ['manualActivationCode', optional(string())],
});
