/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Esim1, esim1Schema } from './esim1';

export interface EsimResponse {
  esim?: Esim1;
}

export const esimResponseSchema: Schema<EsimResponse> = object({
  esim: ['esim', optional(lazy(() => esim1Schema))],
});
