/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { History, historySchema } from './history';

export interface Esim2 {
  /** ID of the eSIM */
  iccid?: string;
  history?: History[];
}

export const esim2Schema: Schema<Esim2> = object({
  iccid: ['iccid', optional(string())],
  history: ['history', optional(array(lazy(() => historySchema)))],
});
