/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface History {
  /** The status of the eSIM at a given time, possible values are 'RELEASED', 'DOWNLOADED', 'INSTALLED', 'ENABLED', 'DELETED', or 'ERROR' */
  status?: string;
  /** The date when the eSIM status changed in the format 'yyyy-MM-ddThh:mm:ssZZ' */
  statusDate?: string;
  /** Epoch value representing the date when the eSIM status changed */
  date?: number;
}

export const historySchema: Schema<History> = object({
  status: ['status', optional(string())],
  statusDate: ['statusDate', optional(string())],
  date: ['date', optional(number())],
});
