/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Package {
  /** ID of the package */
  id?: string;
  /** ISO representation of the package's destination */
  destination?: string;
  /** Size of the package in Bytes */
  dataLimitInBytes?: number;
  /** Min number of days for the package */
  minDays?: number;
  /** Max number of days for the package */
  maxDays?: number;
  /** Price of the package in cents */
  priceInCents?: number;
}

export const packageSchema: Schema<Package> = object({
  id: ['id', optional(string())],
  destination: ['destination', optional(string())],
  dataLimitInBytes: ['dataLimitInBytes', optional(number())],
  minDays: ['minDays', optional(number())],
  maxDays: ['maxDays', optional(number())],
  priceInCents: ['priceInCents', optional(number())],
});
