/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Profile {
  /** ID of the eSIM */
  iccid?: string;
  /** QR Code of the eSIM as base64 */
  activationCode?: string;
}

export const profileSchema: Schema<Profile> = object({
  iccid: ['iccid', optional(string())],
  activationCode: ['activationCode', optional(string())],
});
