/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Profile1 {
  /** ID of the eSIM */
  iccid?: string;
}

export const profile1Schema: Schema<Profile1> = object({
  iccid: ['iccid', optional(string())],
});
