/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Profile, profileSchema } from './profile';
import { Purchase, purchaseSchema } from './purchase';

export interface PurchasesResponse {
  purchase?: Purchase;
  profile?: Profile;
}

export const purchasesResponseSchema: Schema<PurchasesResponse> = object({
  purchase: ['purchase', optional(lazy(() => purchaseSchema))],
  profile: ['profile', optional(lazy(() => profileSchema))],
});
