/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface PurchasesConsumptionResponse {
  /** Remaining balance of the package in bytes */
  dataUsageRemainingInBytes?: number;
  /** Status of the connectivity, possible values are 'ACTIVE' or 'NOT_ACTIVE' */
  status?: string;
}

export const purchasesConsumptionResponseSchema: Schema<PurchasesConsumptionResponse> = object(
  {
    dataUsageRemainingInBytes: [
      'dataUsageRemainingInBytes',
      optional(number()),
    ],
    status: ['status', optional(string())],
  }
);
