/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface PurchasesEditResponse {
  /** ID of the purchase */
  purchaseId?: string;
  /** Start date of the package's validity in the format 'yyyy-MM-ddThh:mm:ssZZ' */
  newStartDate?: string;
  /** End date of the package's validity in the format 'yyyy-MM-ddThh:mm:ssZZ' */
  newEndDate?: string;
  /** Epoch value representing the new start time of the package's validity */
  newStartTime?: number;
  /** Epoch value representing the new end time of the package's validity */
  newEndTime?: number;
}

export const purchasesEditResponseSchema: Schema<PurchasesEditResponse> = object(
  {
    purchaseId: ['purchaseId', optional(string())],
    newStartDate: ['newStartDate', optional(string())],
    newEndDate: ['newEndDate', optional(string())],
    newStartTime: ['newStartTime', optional(number())],
    newEndTime: ['newEndTime', optional(number())],
  }
);
