/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Profile1, profile1Schema } from './profile1';
import { Purchase, purchaseSchema } from './purchase';

export interface PurchasesTopupResponse {
  purchase?: Purchase;
  profile?: Profile1;
}

export const purchasesTopupResponseSchema: Schema<PurchasesTopupResponse> = object(
  {
    purchase: ['purchase', optional(lazy(() => purchaseSchema))],
    profile: ['profile', optional(lazy(() => profile1Schema))],
  }
);
