/**
 * CELITECH APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Purchase {
  /** ID of the purchase */
  id?: string;
  /** ID of the package */
  packageId?: string;
  /** Start date of the package's validity in the format 'yyyy-MM-ddThh:mm:ssZZ' */
  startDate?: string;
  /** End date of the package's validity in the format 'yyyy-MM-ddThh:mm:ssZZ' */
  endDate?: string;
  /** Creation date of the purchase in the format 'yyyy-MM-ddThh:mm:ssZZ' */
  createdDate?: string;
  /** Epoch value representing the start time of the package's validity */
  startTime?: number;
  /** Epoch value representing the end time of the package's validity */
  endTime?: number;
}

export const purchaseSchema: Schema<Purchase> = object({
  id: ['id', optional(string())],
  packageId: ['packageId', optional(string())],
  startDate: ['startDate', optional(string())],
  endDate: ['endDate', optional(string())],
  createdDate: ['createdDate', optional(string())],
  startTime: ['startTime', optional(number())],
  endTime: ['endTime', optional(number())],
});
